[
  {
    invoiceId: 7,
    productId: "5",
    lines: [
      {
        id: 1,
        accountId: "3",
        costCenterId: "2",
        factoryId: "2",
        description: "TEST LINE1",
        taxValueId: "3",
        netAmount: "500.00",
        taxAmount: 115,
        totalAmount: 615,
        businessLineId: "1",
        name: "TEST NEW PRODUCT",
        unitPrice: "55.00",
        quantity: "10.00",
        unitOfMeasure: "KG",
        warehouse: { externalId: "5" },
        totalLineNetAmount: "550.00",
        totalLineTaxAmount: "126.50",
        totalLineAmount: "676.50",
      },
      {
        id: 2,
        accountId: "2",
        costCenterId: "1",
        factoryId: "1",
        description: "TEST LINE2",
        taxValueId: "3",
        netAmount: "50.00",
        taxAmount: 11.5,
        totalAmount: 61.5,
        businessLineId: "2",
        name: "TEST NEW PRODUCT",
        unitPrice: "55.00",
        quantity: "10.00",
        unitOfMeasure: "KG",
        warehouse: { externalId: "5" },
        totalLineNetAmount: 550,
        totalLineTaxAmount: "126.50",
        totalLineAmount: "676.50",
      },
    ],
  },
];
